Repository easybuilders/easybuild-docs, pull requests merged in 2023-10, with the labels that each got.

#214 Fix all typos to make test suite happy
  .github/workflows/test.yml
  docs/removed-functionality.md
  docs/version-specific/eb-help.md
  docs/version-specific/toolchain-opts.md
Labels: bug fix

#205 review "Tracing progress" page
  docs/tracing-progress.md
Labels: review

#216 stick to 2023a for now in toolchain support policy + don't link it to EasyBuild 5.0
  docs/policies/toolchains.md
Labels: bug fix, documentation

#217 wrapping-dependencies page review
  docs/wrapping-dependencies.md
Labels: review

#218 bump version to 4.8.1
  mkdocs.yml
Labels: bug fix, documentation

#222 auto-update docs for EasyBuild v4.8.2
  docs/version-specific/easyconfig-templates.md
  docs/version-specific/eb-help.md
  docs/version-specific/generic-easyblocks.md
  docs/version-specific/supported-software.md
Labels: update

#223 update release notes + bump version for EasyBuild v4.8.2
  docs/index.md
  docs/release-notes.md
  mkdocs.yml
Labels: update
