Repository easybuilders/easybuild-docs, pull requests merged in 2023-09, with the labels that each got.

#210 document `pre_run_shell_cmd_hook` and `post_run_shell_cmd_hook`
  docs/hooks.md
Labels: documentation, enhancement

#211 auto-update docs for EasyBuild v4.8.1
  docs/version-specific/easyblocks.md
  docs/version-specific/easyconfig-parameters.md
  docs/version-specific/eb-help.md
  docs/version-specific/generic-easyblocks.md
  docs/version-specific/supported-software.md
  docs/version-specific/toolchain-opts.md
  docs/version-specific/toolchains.md
Labels: documentation, update

#212 add release notes for EasyBuild v4.8.1
  docs/changelog-docs.md
  docs/release-notes.md
Labels: update

#178 mention that `--trace` will be enabled by default in EasyBuild 5.x
  docs/easybuild-v5/overview-of-changes.md
  docs/tracing-progress.md
Labels: EasyBuild-5.0
