Repository easybuilders/easybuild-docs, pull requests merged in 2023-04, with the labels that each got.

#136 remove block on EasyBuild User Survey from landing page
  docs/index.md
Labels: documentation

#135 only list requirements once on installation page
  docs/installation.md
Labels: documentation

#132 add module cheatsheet + minor tweaks to using-easybuild page
  docs/using-easybuild.md
Labels: review

#141 fix link to list of supported software in EasyBuild release notes
  docs/release-notes.md
Labels: bug fix
