Repository easybuilders/easybuild-docs, pull requests merged in 2023-08, with the labels that each got.

#209 add foss/2023a and intel/2023a to overview of common toolchains
  docs/common-toolchains.md
Labels: documentation, update

#176 Python 2 compatibility review
  docs/python-2-3-compatibility.md
Labels: review

#204 Code style review
  docs/code-style.md
Labels: review

#208 update hooks documentation to cover new hooks: `pre_build_and_install_loop_hook`, `post_build_and_install_loop_hook`, `pre_postiter_hook`, `post_postiter_hook`, `cancel_hook`, `fail_hook`
  docs/hooks.md
Labels: enhancement, update
