Repository easybuilders/easybuild-docs, pull requests merged in 2023-05, with the labels that each got.

#146 fix colours to pass WAVE
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: bug fix

#133 terminology page review: fix EasyBuild version, remove ancient paragraph
  docs/terminology.md
Labels: bug fix, review

#147 Backup modules page review
  docs/backup-modules.md
Labels: review

#149 review & update "Common Toolchains" page + add graph for foss/intel common toolchains and their subtoolchains
  docs/common-toolchains.md
  mkdocs.yml
Labels: review

#152 Revised "workflow example"
  docs/typical-workflow-example-with-wrf.md
  docs/typical-workflow-example.md
  mkdocs.yml
Labels: review

#153 use `"1"` rather than `1` in easystack files, since `1` is treated as a boolean in YAML
  docs/easystack-files.md
Labels: enhancement

#160 auto-update docs for EasyBuild v4.7.2
  .github/workflows/test.yml
  docs/version-specific/easyblocks.md
  docs/version-specific/easyconfig-templates.md
  docs/version-specific/eb-help.md
  docs/version-specific/generic-easyblocks.md
  docs/version-specific/supported-software.md
Labels: documentation, update

#161 add release notes for EasyBuild v4.7.2 + bump version to 4.7.2
  docs/changelog-docs.md
  docs/installation.md
  docs/release-notes.md
  docs/typical-workflow-example.md
  mkdocs.yml
Labels: documentation, update
