Repository easybuilders/easybuild-docs, pull requests merged in 2023-06, with the labels that each got.

#165 switch markdown linter
  .github/workflows/markdown-linting.yml
  .markdownlint.yml
  .mdl.rb
  .mdlrc
  docs/configuration.md
  docs/cray-support.md
  docs/index.md
Labels: enhancement

#137 add initial page with overview of changes in EasyBuild v5.0
  docs/easybuild-v5/overview-of-changes.md
  docs/writing-yeb-easyconfig-files.md
Labels: EasyBuild-5.0

#170 proposed changes in EasyBuild 5
  docs/easybuild-v5/overview-of-changes.md
Labels: EasyBuild-5.0

#171 add link to EasyBuild 5.0 docs on landing page
  docs/easybuild-v5/index.md
  docs/index.md
Labels: documentation, EasyBuild-5.0

#159 rank down release notes page in search results
  docs/release-notes.md
Labels: enhancement

#172 down rank API pages
  docs/gen_ref_pages.py
Labels: enhancement

#173 down rank docs changlog page
  docs/changelog-docs.md
Labels: enhancement

#163 log-files page review
  docs/log-files.md
Labels: review

#166 Review of Locks page
  docs/locks.md
Labels: review
