Repository easybuilders/easybuild-docs, pull requests merged in 2023-12, with the labels that each got.

#231 introduce role-focused landing pages
  docs/index.md
  docs/roles/contributors.md
  docs/roles/developers.md
  docs/roles/end-users.md
  docs/roles/maintainers.md
  docs/roles/user-support.md
Labels: enhancement

#235 auto-update docs for EasyBuild v4.9.0
  docs/version-specific/easyblocks.md
  docs/version-specific/eb-help.md
  docs/version-specific/generic-easyblocks.md
  docs/version-specific/supported-software.md
Labels: documentation

#234 add 2023b common toolchains to overview
  docs/common-toolchains.md
Labels: documentation

#236 move 2020b to deprecated toolchains
  docs/common-toolchains.md
  docs/policies/toolchains.md
Labels: documentation

#237 update release notes + bump version for EasyBuild v4.9.0
  docs/release-notes.md
  mkdocs.yml
Labels: update
