Repository easybuilders/easybuild-docs, pull requests merged in 2023-01, with the labels that each got.

#86 add script to auto-generate version-specific pages
  .github/workflows/markdown-linting.yml
  .github/workflows/test.yml
  docs/version-specific/config-file-constants.md
  docs/version-specific/easyblocks.md
  docs/version-specific/easyconfig-constants.md
  docs/version-specific/easyconfig-license-constants.md
  docs/version-specific/easyconfig-parameters.md
  docs/version-specific/easyconfig-templates.md
  docs/version-specific/eb-help.md
  docs/version-specific/eb-list-toolchains.md
  docs/version-specific/example_easyconfigs/Binary.eb
  docs/version-specific/example_easyconfigs/Bundle.eb
  docs/version-specific/example_easyconfigs/CMakeMake.eb
  docs/version-specific/example_easyconfigs/ConfigureMake.eb
  docs/version-specific/example_easyconfigs/ConfigureMakePythonPackage.eb
  docs/version-specific/gen_easyblocks_docs.py
  docs/version-specific/generic-easyblocks.md
  docs/version-specific/index.md
  docs/version-specific/supported-software.md
  docs/version-specific/toolchain-opts.md
  docs/version-specific/update-version-specific-docs.sh
Labels: porting-to-mkdocs

#79 use mkdocstrings to generate API docs
  .flake8
  .github/workflows/deploy.yml
  .github/workflows/flake8.yml
  .github/workflows/test.yml
  docs/gen_api_pages.py
  docs/gen_ref_pages.py
  mkdocs.yml
  requirements.txt
Labels: porting-to-mkdocs

#90 Autogenerated markdown fixes
  docs/version-specific/config-file-constants.md
  docs/version-specific/easyconfig-templates.md
  docs/version-specific/eb-list-toolchains.md
  docs/version-specific/generic-easyblocks.md
  docs/version-specific/supported-software.md
  docs/version-specific/toolchain-opts.md
  docs/version-specific/update-version-specific-docs.sh
Labels: porting-to-mkdocs

#91 Correct internal links on toolchain opts page
  docs/version-specific/toolchain-opts.md
  docs/version-specific/update-version-specific-docs.sh
Labels: bug fix

#89 Allow generation without clone of easybuild-framework and move location of source
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  docs/gen_ref_pages.py
  mkdocs.yml
Labels: porting-to-mkdocs

#92 formatting fixes for auto-generated docs
  docs/version-specific/easyconfig-parameters.md
  docs/version-specific/easyconfig-templates.md
  docs/version-specific/eb-help.md
Labels: bug fix, porting-to-mkdocs

#93 update overview of common toolchains with foss/2022b and intel/2022b
  docs/common-toolchains.md
Labels: update

#94 add EasyBuild 4.7.0 release notes
  docs/changelog-docs.md
  docs/release-notes.md
Labels: documentation

#97 use the main branch of the framework code to generate API docs
  .github/workflows/deploy.yml
  .github/workflows/test.yml
Labels: bug fix

#105 Fix indentation for Easystack examples
  docs/easystack-files.md
Labels: bug fix

#108 add subsection to README on writing + using MarkDown Live Preview or HackMD
  README.md
Labels: documentation

#109 add missing redirect for Useful_links page in old docs
  mkdocs.yml
  requirements.txt
Labels: bug fix
