Repository easybuilders/easybuild-docs, pull requests merged in 2024-04, with the labels that each got.

#245 fix toolchain graph
  docs/common-toolchains.md
Labels: bug fix

#248 auto-update docs for EasyBuild v4.9.1
  docs/version-specific/easyblocks.md
  docs/version-specific/easyconfig-license-constants.md
  docs/version-specific/easyconfig-parameters.md
  docs/version-specific/eb-help.md
  docs/version-specific/generic-easyblocks.md
  docs/version-specific/supported-software.md
Labels: documentation

#249 update release notes + bump version for EasyBuild v4.9.1
  docs/release-notes.md
  mkdocs.yml
Labels: documentation

#250 update docs for release of EasyBuild v4.9.1
  docs/common-toolchains.md
  docs/configuration.md
  docs/easybuild-v5/changes-in-default-configuration.md
  docs/easybuild-v5/enhancements.md
  docs/easybuild-v5/index.md
  docs/easybuild-v5/overview-of-changes.md
  docs/easybuild-v5/proposed-changes.md
  docs/installation.md
  docs/manipulating-dependencies.md
  docs/release-notes.md
  docs/unit-tests.md
  docs/version-specific/easyblocks.md
  docs/version-specific/easyconfig-license-constants.md
  docs/version-specific/easyconfig-parameters.md
  docs/version-specific/eb-help.md
  docs/version-specific/generic-easyblocks.md
  docs/version-specific/supported-software.md
  mkdocs.yml
Labels: documentation

#251 fix toolchain diagram
  docs/common-toolchains.md
Labels: bug fix

#252 fix counts on top of release notes for EasyBuild 4.9.1
  docs/release-notes.md
Labels: bug fix, documentation

#247 update table on transitioning to `run_shell_cmd` to also cover `run_cmd_qa` options
  docs/easybuild-v5/run_shell_cmd.md
Labels: EasyBuild-5.0

#221 Review of progress-bars
  docs/progress-bars.md
Labels: documentation

#220 Review of manipulating dependencies
  docs/manipulating-dependencies.md
Labels: documentation
