Repository easybuilders/easybuild-docs, pull requests merged in 2024-09, with the labels that each got.

#267 example of adding a hook conditional on EasyBuild version
  docs/hooks.md
Labels: enhancement

#268 fix iimkl for 2022a
  docs/common-toolchains.md
Labels: bug fix, documentation

#269 fix links to overview of supported software
  docs/index.md
  docs/release-notes.md
  mkdocs.yml
Labels: bug fix, documentation

#270 add `foss/2024a` + `intel/2024a` toolchains to overview of common toolchains
  docs/common-toolchains.md
Labels: documentation, update

#272 add release notes for EasyBuild v4.9.3
  docs/release-notes.md
  mkdocs.yml
Labels: documentation, update

#274 document `--from-commit` and `--include-easyblocks-from-commit`
  docs/integration-with-github.md
  docs/release-notes.md
Labels: documentation, enhancement

#277 update release notes for EasyBuild v4.9.4
  docs/release-notes.md
Labels: documentation, update

#275 add granular exit codes to the enhacements of EasyBuild v5
  docs/easybuild-v5/enhancements.md
Labels: documentation, enhancement
