Repository easybuilders/easybuild-docs, pull requests merged in 2025-01, with the labels that each got.

#289 revise landing page with overview of changes in EasyBuild v5.0
  docs/easybuild-v5/backwards-incompatible-changes.md
  docs/easybuild-v5/changes-in-default-configuration.md
  docs/easybuild-v5/deprecated-functionality.md
  docs/easybuild-v5/enhancements.md
  docs/easybuild-v5/index.md
  docs/easybuild-v5/overview-of-changes.md
  docs/easybuild-v5/policies.md
  docs/easybuild-v5/python36-required.md
  docs/easybuild-v5/removed-functionality.md
  docs/easybuild-v5/run_shell_cmd.md
  docs/python-2-3-compatibility.md
  docs/roles/contributors.md
  docs/roles/developers.md
  docs/roles/end-users.md
  docs/roles/maintainers.md
  docs/roles/user-support.md
  mkdocs.yml
Labels: EasyBuild-5.0

#291 mention `--from-pr` as a way to install EasyBuild v5.0.0beta1 + enable copy button in code blocks
  docs/easybuild-v5/release-candidates.md
  mkdocs.yml
Labels: documentation

#292 document how to generate a crates list
  docs/writing-easyconfig-files.md
Labels: documentation, enhancement
